#!/usr/bin/env node
// Regenerates src/icons.ts from the heroicons package. Add an entry to
// ICONS below and re-run `npm run icons` to add a new icon.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const heroiconsDir = path.join(__dirname, "../node_modules/heroicons/24");

/** @type {Record<string, { slug: string; variant?: "outline" | "solid"; size?: number }>} */
const ICONS = {
  X: { slug: "x-mark" },
  Bars3: { slug: "bars-3" },
  ChevronLeft: { slug: "chevron-left", size: 16 },
  ChevronRight: { slug: "chevron-right", size: 16 },
  Cog: { slug: "cog-6-tooth", size: 20 },
  Info: { slug: "information-circle", size: 20 },
  QuestionMarkCircle: { slug: "question-mark-circle", size: 20 },
  Pencil: { slug: "pencil", size: 16 },
  Trash: { slug: "trash", size: 16 },
  Plus: { slug: "plus", size: 16 },
  ListBullet: { slug: "list-bullet" },
  CurrencyDollar: { slug: "currency-dollar", size: 16 },
  Home: { slug: "home", size: 16 },
  MapPin: { slug: "map-pin", size: 16 },
  Clock: { slug: "clock", size: 16 },
  Tag: { slug: "tag", size: 16 },
  Calendar: { slug: "calendar", size: 16 },
  ArrowsPointingOut: { slug: "arrows-pointing-out", size: 16 },
  Map: { slug: "map", size: 16 },
  CheckCircle: { slug: "check-circle", size: 16 },
  Sun: { slug: "sun", size: 16 },
  ShieldExclamation: { slug: "shield-exclamation", size: 16 },
  ArrowPath: { slug: "arrow-path", size: 12 },
  ArrowRight: { slug: "arrow-right", size: 12 },
  Link: { slug: "link", size: 16 },
  Heart: { slug: "heart", size: 16 },
  HeartSolid: { slug: "heart", variant: "solid", size: 16 },
  Eye: { slug: "eye", size: 16 },
  EyeSlash: { slug: "eye-slash", size: 16 },
  ShieldCheck: { slug: "shield-check", size: 16 },
  UserCircle: { slug: "user-circle", size: 20 },
  ClipboardDocumentList: { slug: "clipboard-document-list", size: 18 },
  CpuChip: { slug: "cpu-chip", size: 18 },
  Folder: { slug: "folder", size: 18 },
  ChevronDown: { slug: "chevron-down", size: 16 },
  Document: { slug: "document", size: 18 },
  Squares2x2: { slug: "squares-2x2", size: 18 },
  ChatBubbleLeftRight: { slug: "chat-bubble-left-right", size: 18 },
  ArrowTopRightOnSquare: { slug: "arrow-top-right-on-square", size: 16 },
};

/**
 * Extracts the inner markup (paths, etc.) of an SVG file's root element.
 * @param {string} svg
 * @returns {string}
 */
function innerOf(svg) {
  const match = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!match) {
    throw new Error("Could not parse SVG root element");
  }
  return match[1].trim().replace(/\s+/g, " ");
}

/**
 * @param {string} name
 * @param {{ slug: string; variant?: "outline" | "solid"; size?: number }} spec
 */
async function renderIcon(name, spec) {
  const variant = spec.variant ?? "outline";
  const filePath = path.join(heroiconsDir, variant, `${spec.slug}.svg`);
  const raw = await readFile(filePath, "utf8");
  const inner = innerOf(raw);
  const defaultSize = spec.size ?? 18;

  const attrs =
    variant === "solid"
      ? `fill="currentColor"`
      : `fill="none" stroke-width="1.5" stroke="currentColor"`;

  return `export const icon${name} = (size = ${defaultSize}) =>
  svg\`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" ${attrs} width=\${size} height=\${size} aria-hidden="true">${inner}</svg>\`;`;
}

const entries = await Promise.all(
  Object.entries(ICONS).map(([name, spec]) => renderIcon(name, spec))
);

const header = `import { svg } from "lit";

// GENERATED by scripts/generate-icons.mjs — do not edit;
// add names to the ICONS list in the script and re-run \`npm run icons\`.
`;

const output = `${header}\n${entries.join("\n\n")}\n`;

await writeFile(path.join(__dirname, "../src/icons.ts"), output, "utf8");
console.log(`Wrote src/icons.ts with ${entries.length} icons`);
